# Generated by Django 4.0.4 on 2022-05-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='num',
            name='usernum',
        ),
        migrations.AddField(
            model_name='num',
            name='lottos',
            field=models.CharField(default='[1, 2, 3, 4, 5, 6]', max_length=255),
        ),
        migrations.AddField(
            model_name='num',
            name='num_lotto',
            field=models.IntegerField(default=5),
        ),
    ]
